### ISSUE TITLE
String interpolation doesn't work with expressions involving locals

### ISSUE THREAD

**Issue by randrews** [norman/lua-haml#12]
This works:

```
- foo = {1, 2, 3}
%div{:class => "span#{foo[1]}"}
```

This doesn't:

```
- local foo = {1, 2, 3}
%div{:class => "span#{foo[1]}"}
```

But, this also works:

```
- local foo = {1, 2, 3}
- local f = foo[1]
%div{:class => "span#{f}"}
```

Seems to be something in interpolate_value in renderer.lua, it does one thing for variable names and another for expressions, and the branch for expressions isn't looking in the correct environment for variables.

**Comment by randrews** [comment]
Spoke too soon; the third example doesn't work. It renders:

```
<div class="span#{f}"></div>
```

So, apparently it just doesn't work with locals full stop, it doesn't require the local to be in an expression.

**Comment by norman** [comment]
`intrpolate_value` relies on getfenv, which doesn't give you access to locals. The workaround LuaHaml currently offers is to assign values to an already-initialized `locals` table, so this will work:

``` haml
- locals['foo'] = "a"                                                           
%div{:class => "span-#{foo}"}
```

To be honest it's been a while since I looked at the problem and don't recall why I did it this way. Probably the best way to implement this is to avoid all the interpolation function silliness completely. Currently the Haml above precompiles to this (only including the relevant line):

``` lua
r:b(r:attr({["class"] = r:interp("span-#{foo}"), }))
```

If we changed this to compile to:

``` lua
r:b(r:attr({["class"] = "span-" .. foo})) 
```

then it would be faster, simpler and a whole lot less embarrassing for me. :)

**Comment by randrews** [comment]
Yeah, I agree, I think the real issue is that scoping in Haml files doesn't act like it looks like it does, and there's no easy way to make it do so. :)

It just appears weird because this only affects interpolation, I can do this fine with local vars:

```
- for n = 1, 10 do
  %td= n
```

Now that making non-locals is safe (doesn't overwrite the actual global scope) then this is a good workaround though.

**Comment by norman** [comment]
I've almost got the locals support finished now, I just need to tweak the interpolation handling inside content. I'll push something later today.

**Comment by randrews** [comment]
Cool, thanks!

**Comment by norman** [comment]
@randrews this change is now pushed to master, give it a try and let me know if anything breaks down for you.
